backend/models/Category.php
<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "category".
 *
 * @property int $category_id
 * @property int $parent_id
 * @property int $is_active
 * @property int $is_main
 * @property string $url
 * @property string $name
 * @property string $description
 * @property string $long_description
 * @property int $sort_order
 * @property string $icon
 * @property string $image
 * @property string $background_image
 * @property string $background_image_header
 *
 * @property TourCategory[] $tourCategories
 * @property Tour[] $tours
 */
class Category extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'category';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['parent_id', 'is_active', 'is_main', 'url', 'name', 'description', 'long_description', 'sort_order', 'icon', 'image', 'background_image', 'background_image_header'], 'required'],
            [['parent_id', 'is_active', 'is_main', 'sort_order'], 'integer'],
            [['description', 'long_description'], 'string'],
            [['url', 'name', 'icon', 'image', 'background_image', 'background_image_header'], 'string', 'max' => 255],
            [['url'], 'unique'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'category_id' => 'Category ID',
            'parent_id' => 'Parent ID',
            'is_active' => 'Is Active',
            'is_main' => 'Is Main',
            'url' => 'Url',
            'name' => 'Name',
            'description' => 'Description',
            'long_description' => 'Long Description',
            'sort_order' => 'Sort Order',
            'icon' => 'Icon',
            'image' => 'Image',
            'background_image' => 'Background Image',
            'background_image_header' => 'Background Image Header',
        ];
    }

    /**
     * Gets query for [[TourCategories]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getTourCategories()
    {
        return $this->hasMany(TourCategory::className(), ['category_id' => 'category_id']);
    }

    /**
     * Gets query for [[Tours]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getTours()
    {
        return $this->hasMany(Tour::className(), ['tour_id' => 'tour_id'])->viaTable('tour_category', ['category_id' => 'category_id']);
    }
}

frontend/models/Category.php
<?php

namespace frontend\models;

use Yii;

/**
 * This is the model class for table "category".
 *
 * @property int $id
 * @property int $parent_id
 * @property string $name
 * @property string $description
 * @property string $long_description
 * @property string $url
 * @property string $icon
 * @property string $image
 * @property int $is_active
 * @property int $sort
 *
 * @property TourCategory[] $tourCategories
 * @property Tours[] $tours
 */
class Category extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'category';
    }


    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'name' => 'Name',
            'description' => 'Description',
            'long_description' => 'Long Description',
        ];
    }

    /**
     * Gets query for [[TourCategories]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getTourCategories()
    {
        return $this->hasMany(TourCategory::className(), ['category_id' => 'id']);
    }

    /**
     * Gets query for [[Tours]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getTours()
    {
        return $this->hasMany(Tours::className(), ['id' => 'tour_id'])->viaTable('tour_category', ['category_id' => 'id']);
    }

    public function getIcon()
    {
        if (empty($this->icon) ||
            !is_file(Yii::getAlias("@frontend") . '/web/images/category/icons/' . $this->icon)) {
            return '/images/category/icons/placeholder.png';
        }
        return '/images/category/icons/' . $this->icon;
    }

    public function getImage()
    {
        if (empty($this->image) ||
            !is_file(Yii::getAlias("@frontend") . '/web/images/category/' . $this->image)) {
            return '/images/category/placeholder.png';
        }
        return '/images/category/' . $this->image;
    }
}

backend/controllers/CategoryController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\Category;
use backend\models\CategorySearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * CategoryController implements the CRUD actions for Category model.
 */
class CategoryController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Category models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new CategorySearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Category model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Category model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Category();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Category model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Category model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Category model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Category the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Category::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

frontend/controllers/CategoryController.php
<?php

namespace frontend\controllers;

use frontend\models\TourCategory;
use Yii;
use frontend\models\Category;
use frontend\models\CategorySearch;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * CategoryController implements the CRUD actions for Category model.
 */
class CategoryController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
        ];
    }

    /**
     * Lists all Category models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new CategorySearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Category model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $categories = Category::find()
            ->where(['is_active' => 1])
            ->all();

        $tourProvider = new ActiveDataProvider([
            'query' => TourCategory::find()->where(['category_id' => $id]),
            'pagination' => [
                'pageSize' => 10,
            ],
        ]);

        return $this->render('view', [
            'model' => $this->findModel($id),
            'categories' => $categories,
            'tourProvider' => $tourProvider
        ]);
    }


    /**
     * Finds the Category model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Category the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Category::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

frontend/views/category/_category_item.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
?>
<a href="<?= Url::to(['category/view', 'id' => $model->id]); ?>" class="list-group-item list-group-item-action">
    <div class="d-flex">
        <div class="p-3">
            <?= Html::img($model->getIcon(), ['width' => '50px']) ?>
        </div>
        <div class="p-3">
            <h4>
                <?= Html::encode($model->name) ?>
            </h4>

        </div>
    </div>


</a>

frontend/views/category/_tour_item.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
?>

<div class="list-group-item d-flex">
    <div class="pr-2">
        <?= Html::img($model->tour->getImage(), ['style' => 'width: 150px; margin: 3px']) ?>
    </div>
    <div class="pr-2">
        <h4>
            <a href="<?= Url::to(['tour/view', 'id' => $model->tour->id, 'category_id' => $model->category_id]); ?>">
                <?= Html::encode($model->tour->title) ?>
            </a>
        </h4>
        <a href="<?= Url::to(['event/index', 'EventSearch[tour_id]' => $model->tour->id]) ?>" class="btn btn-primary">Графік поїздок</a>
    </div>


</div>

frontend/views/category/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\ListView;

/* @var $this yii\web\View */
/* @var $searchModel frontend\models\CategorySearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Наші тури';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="category-index">

    <h1><?= Html::encode($this->title) ?></h1>


    <?= ListView::widget([
        'dataProvider' => $dataProvider,
        'options' => [
            'class' => 'list-group',
        ],
        'itemOptions' => [
            'tag' => false,
        ],
        'layout' => "{summary}\n{items}\n{pager}",
        'summaryOptions' => ['style' => "width: 100%; margin: 5px"],
        'itemView' => '_category_item',
        'viewParams' => ['id' => $model->id]
    ]);
    ?>


</div>

frontend/views/category/view.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\DetailView;
use yii\widgets\ListView;

/* @var $this yii\web\View */
/* @var $model frontend\models\Category */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Наші тури', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="category-view">

    <h1><?= Html::encode($this->title) ?></h1>
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-6 col-lg-3">
                <div class="list-group">
                    <?php foreach($categories as $categoryItem): ?>
                        <?php $active = ($categoryItem->id == $model->id) ? "active" : ""; ?>
                        <a href="<?= Url::to(['category/view', 'id' => $categoryItem->id]); ?>" class="list-group-item <?= $active ?>">
                            <?= $categoryItem->name ?>
                        </a>
                    <?php endforeach ?>
                </div>
            </div>
            <div class="col-12 col-md-6 col-lg-9">
                <?= $model->long_description ?>
                <div class="container-fluid">
                    <?= ListView::widget([
                        'dataProvider' => $tourProvider,
                        'options' => [
                            'class' => 'list-group',
                        ],
                        'itemOptions' => [
                            'tag' => false,
                        ],
                        'layout' => "{summary}\n{items}\n{pager}",
                        'summaryOptions' => ['style' => "width: 100%; margin: 5px"],
                        'itemView' => '_tour_item',
                        'viewParams' => ['id' => $model->id]
                    ]);
                    ?>
                </div>
            </div>
        </div>
    </div>




</div>